### ISSUE TITLE
[bug] Multiple spaces are replaced with a single space

### ISSUE THREAD

**Issue by epoberezkin** [finnp/json-lexer#14]
Both in whitespace and inside strings.

```javascript
var result = lexer("{\n  \"  foo  \": 1\n}");
result.reduce((memo, token) => memo + token.raw, ''); // "{\n \" foo \": 1\n}"
```

**Comment by finnp** [comment]
Hey @epoberezkin,

I was not able to reproduce this bug. Can you check again on this? I was testing with version json-lexer@1.1.1. What environment are you running this in?

**Comment by epoberezkin** [comment]
It's the bug in runkit it seems:

https://runkit.com/esp/587621dc9462c70013b1fd17

They don't show the string correctly.
Thank you.

**Comment by finnp** [comment]
Ah weird, thanks for looking into it 👍

**Comment by epoberezkin** [comment]
No problem - I sent them a message.
